spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_repo
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # New database is created when app starts and destroyed when app stops
      ddl-auto: create
      # Show sql when spring data jpa performs query
      show-sql: true
      properties:
        hibernate:
          # Format queries
          format_sql: true